services:
  - type: web
    name: markchavez-dev
    runtime: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /_next/static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
